clair:
  image: quay.io/coreos/clair
  links:
    - postgres
  ports:
    - 6060:6060
    - 6061:6061
  volumes:
    - ./config:/config
    - /tmp
  command:
    - -config=/config/config.yaml

analyze-local-images:
  build: .
  net: container:clair
  volumes_from:
    - clair
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro

postgres:
  image: postgres:9.4
  environment:
    - POSTGRES_USER=clair
    - POSTGRES_PASSWORD=clair
    - PGDATA=/var/lib/postgresql/data/clair
  volumes_from:
    - postgres-data

postgres-data:
  image: postgres:9.4
  volumes:
    - /var/lib/postgresql/data/clair
  entrypoint:
    - /bin/bash
  command:
    - "echo run once"
